#!/usr/bin/env python3
import socket
import sys
import requests
import os

def add_task(to_add):
    to_add = ' '.join(to_add)

    headers = {
        'content-type': 'application/json'
    }
    data = {
        "nova tarefa": to_add
    }
    res = requests.post('http://'+ip_address+'/Tarefa/', headers=headers, json=data)
    print('Response: ',res.status_code)
    
def list_all():
    res = requests.get('http://'+ip_address+'/Tarefa/')
    print(res.text)

def search_one(task_id):
    res = requests.get('http://'+ip_address+'/Tarefa/'+task_id)
    print(res.text)

def erase_one(task_id):
    res = requests.delete('http://'+ip_address+'/Tarefa/'+task_id)
    print('Response: ',res.status_code)

def update_one(atributos):
    task_id = atributos[0]
    to_update = ' '.join(atributos[1:])

    headers = {
        'content-type': 'application/json'
    }
    data = {
        "tarefa atualizada": to_update
    }
    res = requests.put('http://'+ip_address+'/Tarefa/'+task_id, headers=headers, json=data)
    print('Response: ',res.status_code)

def healthcheck():
    res = requests.get('http://'+ip_address+'/healthcheck/')
    if(res.status_code == 200):
        print('\033[1;32;49mServidor funcionando normalmente\033[0;49;49m --- resposta {}'.format(res.status_code))
    else:
        print('\033[1;31;49mServidor com problemas\033[0;49;49m --- resposta {}'.format(res.status_code))

ip_address = os.environ.get("BASIC_URL")

try:
    argument = sys.argv[1]
    returned = ""

    if (argument == "adicionar"):
        add_task(sys.argv[2:])

    elif (argument == "listar"):
        list_all()

    elif (argument == "buscar"):
        search_one(sys.argv[2])

    elif (argument == "apagar"):
        erase_one(sys.argv[2])

    elif (argument == "atualizar"):
        update_one(sys.argv[2:])

    elif (argument == "checar"):
        healthcheck()

    elif (argument == "help"):
        print('''
Você digitou um comando inválido. Veja abaixo as opções de comando para fazer o que deseja.

    1) ./tarefa \033[1;32;49mlistar\033[0;49;49m -
        Lista todas as tarefas existentes
        
    2) ./tarefa \033[1;32;49madicionar \033[1;33;49m[tarefa para ser adicionada]\033[0;49;49m -
        Adiciona uma nova tarefa na sua lista
        
    3) ./tarefa \033[1;32;49mbuscar \033[1;33;49m[id]\033[0;49;49m -
        Busca a tarefa atrelada ao id colocado e te retorna o que ela é
    
    4) ./tarefa \033[1;32;49mapagar \033[1;33;49m[id]\033[0;49;49m -
        Apaga a tarefa atrelada ao id colocado

    5) ./tarefa \033[1;32;49matualizar \033[1;33;49m[id] [nova valor da tarefa]\033[0;49;49m -
        Atualiza a tarefa atrelada ao id colocado

    6) ./tarefa \033[1;32;49mchecar\033[0;49;49m -
        Checa que o servidor esta funcionando normalmente
    ''')
    else:
        print("Você digitou um comando inválido tente digitar \033[1;32;49mtarefa \033[1;33;49mhelp\033[0;49;49m para ver as opções")
except Exception as e:
    print(e)
